# Generated by Django 2.0.6 on 2018-07-11 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_auto_20180711_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='alternative_names',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='language',
            name='iso_639_1_code',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='language',
            name='iso_639_2_code',
            field=models.CharField(default='', max_length=3, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
