# Generated by Django 2.0.6 on 2018-07-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_auto_20180711_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='example_sentence',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='word',
            name='part_of_speech',
            field=models.CharField(choices=[('NOUN', 'NOUN'), ('PRONOUN', 'PRONOUN'), ('VERB', 'VERB'), ('ADJECTIVE', 'ADJECTIVE'), ('ADVERB', 'ADVERB'), ('PREPOSITION', 'PREPOSITION'), ('CONJUCTION', 'CONJUCTION'), ('INTERJECTION', 'INTERJECTION')], default='', max_length=50),
            preserve_default=False,
        ),
    ]
