# Generated by Django 2.0.6 on 2018-07-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_auto_20180711_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='iso_639_1_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
