# Generated by Django 2.0.6 on 2018-07-25 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_auto_20180719_2337'),
        ('translation', '0004_auto_20180720_1331'),
    ]

    operations = [
    ]
