# Generated by Django 2.0.6 on 2018-08-13 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0006_translation_example_sentence'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='part_of_speech',
            field=models.CharField(choices=[('NOUN', 'NOUN'), ('PRONOUN', 'PRONOUN'), ('VERB', 'VERB'), ('ADJECTIVE', 'ADJECTIVE'), ('ADVERB', 'ADVERB'), ('PREPOSITION', 'PREPOSITION'), ('CONJUCTION', 'CONJUCTION'), ('INTERJECTION', 'INTERJECTION')], default='NOUN', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_payment', to='translation.Translation'),
        ),
    ]
