# Generated by Django 2.0.6 on 2018-08-13 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0006_translation_example_sentence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='translation_payment', to='translation.Translation'),
        ),
    ]
