# Generated by Django 2.0.6 on 2018-08-24 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0007_auto_20180813_2216'),
        ('translation', '0007_auto_20180813_0824'),
    ]

    operations = [
    ]
